# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='TimeStamp.proto',
  package='',
  serialized_pb='\n\x0fTimeStamp.proto\"]\n\x0bpbTimeStamp\x12\x0e\n\x06theSec\x18\x01 \x02(\x01\x12\x0e\n\x06theMJD\x18\x02 \x02(\x03\x12\r\n\x05\x66lags\x18\x03 \x01(\x05\x12\x10\n\x08refFrame\x18\x04 \x01(\x05\x12\r\n\x05units\x18\x05 \x01(\x05')




_PBTIMESTAMP = descriptor.Descriptor(
  name='pbTimeStamp',
  full_name='pbTimeStamp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='theSec', full_name='pbTimeStamp.theSec', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='theMJD', full_name='pbTimeStamp.theMJD', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='flags', full_name='pbTimeStamp.flags', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='refFrame', full_name='pbTimeStamp.refFrame', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='units', full_name='pbTimeStamp.units', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=19,
  serialized_end=112,
)

DESCRIPTOR.message_types_by_name['pbTimeStamp'] = _PBTIMESTAMP

class pbTimeStamp(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PBTIMESTAMP
  
  # @@protoc_insertion_point(class_scope:pbTimeStamp)

# @@protoc_insertion_point(module_scope)
